### ISSUE TITLE
Roadmap to next version

### ISSUE THREAD

**Issue by sergeche** [endorphinjs/endorphin#4]
* [ ] Detach attributes and events from `injector`, store local ref with change set, when required.
* [x] Set unmount function as a property of mount function to skip `addDisposeCallback` trash
* [ ] Ensure injector as simple as possible
